export * from '@/pages/Dashboard/components/DashboardNews'
export * from '@/pages/Dashboard/components/DashboardFollow'
export * from '@/pages/Dashboard/components/DashboardLeftList'
export * from '@/pages/Dashboard/components/DashboardTags'
export * from '@/pages/Dashboard/components/DashboardReadingList'
export * from '@/pages/Dashboard/components/DashboardNewsLikes'
export * from '@/pages/Dashboard/components/SelectionDashboard'
export * from '@/pages/Dashboard/components/TitleDashboard'
export { default as ModalPublicNews } from '@/pages/Dashboard/components/ModalPublicNews'
