export * from '@/pages/News/components/ButtonNewsIcon'
export * from '@/pages/News/components/NewsDetail'
export * from '@/pages/News/components/NewsSideLeft'
export * from '@/pages/News/components/NewsSideRight'
export * from '@/pages/News/components/NewsComment'
export * from '@/pages/News/components/NewsSideRightUser'
export * from '@/pages/News/components/NewsSideRightRelationUser'
export * from '@/pages/News/components/NewsSideRightRelation'
