export { default as NewsDetail } from '@/pages/News/components/NewsDetail'
export { default as NewsSideLeft } from '@/pages/News/components/NewsSideLeft'
export * from '@/pages/News/components/NewsSideRight'
export { default as NewsComment } from '@/pages/News/components/NewsComment'
export { default as NewsAction } from '@/pages/News/components/NewsAction'
export { default as NewsContent } from '@/pages/News/components/NewsContent'
export * from '@/pages/News/components/ModalImageNews'
