export * from '@/pages/Auth'
export * from '@/pages/News'
export { default as Profile } from '@/pages/Profile'
export { default as Settings } from '@/pages/Settings'
export { default as Dashboard } from '@/pages/Dashboard'
export * from '@/pages/Tags'
export { default as ReadingList } from '@/pages/ReadingList'
export { default as Signout } from '@/pages/Signout'
export { default as ProfileUser } from '@/pages/ProfileUser'
